### ISSUE TITLE
nwg-lock behaves badly on system sleep

### ISSUE THREAD

**Issue by nergdron** [nwg-piotr/nwg-shell-config#68]
I'm using `nwg-shell-config 0.5.29-1` on Arch, running on hyprland. when I configure swayidle as follows, everything works correctly, my screen locks properly after the first timeout, goes to sleep after the second, and wakes from sleep after moving the mouse or pressing a button on the keyboard:

```
swayidle -w \
  timeout 30 "swaylock -f -i /path/to/wallpaper.jpg" \
  timeout 90 "systemctl suspend" &
```
however, if I use the nwg configuration for swaylock, setting the first timeout to 300 and the sleep timeout to 900, and the sleep command to `systemctl suspend`, I see the following in the process listing, and it behaves badly in the following way:

* ps output shows: `swayidle timeout 30 nwg-lock timeout 90 systemctl suspend`
* system correctly locks after first timeout, and can be correctly unlocked
* if the sleep timeout is exceeded, system does *not* sleep correctly, entire screen turns full red #ff0000, and while cursor is visible, it is no longer possible to unlock the system.
  * apps still run in the background correctly, so this isn't crashing wayland or hyprland or anything.
* can switch to a virtual terminal with ctl-alt-f1, and get to the login manager, but resuming the session still doesn't fix things, it stays dead until the hyprland session is killed from a virtual terminal or the system is rebooted

I'm not sure what `nwg-lock` is doing differently than `swaylock`, but it's super busted in my usage. I thought at first it might be related to the disabled monitor problems we saw with `nwg-displays`, but I've actually got my second and third outputs still mirrored, and `nwg-displays` still runs correctly, so I really don't have a clue.

any thoughts on how I could run this differently to figure out what's going wrong?

**Comment by nwg-piotr** [comment]
I observed such an issue some time ago, bot I can't make it happen any longer, at least on the machine at the office. Everything works as expected now. Will try again when I'm home.

**Comment by nwg-piotr** [comment]
OK, got some clue. On my side commands in the 1st and 2nd timeout work well one by one, but I end up in the red screen of death if I lock the screen first manually, either with the `swaylock` or `nwg-lock` command, and wait for the command on 1st time to fire up automatically. It started to happen since the 0.33.0 Hyprland version. Previously swaylock behaved the same way on sway and Hyprland.

Sway does not allow the second instance of swaylock to run. Launch sway and try running `sleep 10 && swaylock` in one terminal, and then `swaylock` in another terminal. After 10 seconds in the first one you'll see:

```text
$ sleep 10 && swaylock
2024-01-03 12:36:11 - [swaylock-1.7.2/main.c:321] Failed to lock session -- is another lockscreen running?
```

The same experiment on Hyprland leads us to the red screen. 

The nwg-lock command just reads the shell settings, and uses your locker of choice accordingly.

**Comment by nwg-piotr** [comment]
The reply above is probably incorrect. Need to make some more testing.

**Comment by nwg-piotr** [comment]
OK, the problem was that nwg-lock, before starting, would attempt to kill the running locker instance, which was:

1. unnecessary (neither swaylock nor gtklock allow multiple instances);
2. unsafe;
3. leading to the red screen crash on swaylock.

I deleted this part of code, together with some other obsolete stuff. I also removed gtklock from Hyprland settings, as it no longer works here.
